### ISSUE TITLE
Can't connect to either ethernet or wireless

### ISSUE THREAD

**Issue by NutymcNuty** [ConnorRigby/xlink-kai#1]
Hi ConnorRigby, I can't seem to get connect to my router properly with the xlink config text document. any chance you could give a better example as its stuck at nonblocking pool is initialized.
I'm on a raspberry pi 3 with the latest version installed to my sd card.

**Comment by ConnorRigby** [comment]
Sorry i was not emailed about this message for some reason. Are you trying to use Wifi or ethernet?

**Comment by ConnorRigby** [comment]
Oh sorry about that i didn't read the title carefully enough. Can i see your config text file? (without your password or anything please)

**Comment by DasKatzchen** [comment]
I'm getting the same behavior. It hangs at nonblocking pool initialized, right after detecting the built in Ethernet. Several lines before that it complains that it can't find the specified bootloader and autoloads shoehorn.boot instead, perhaps related?

**Comment by NutymcNuty** [comment]
ConnorRigby, i don't currently have it setup again i ended up using raspbian and doing it all manually. ill re download it now again. also by anychance does this os have the ability to connect wirelessly and then use the ethernet port directly to the xbox?

**Comment by NutymcNuty** [comment]
I have it as: interface wlan0, ssid=Network Not Found, psk=74andthenabunchofletters, key_mgmt=WPA-PSK
i've also tried via ethernet and nothing happens

**Comment by NutymcNuty** [comment]
i tried 1.1 and it seems to get further but not much. can someone show their xlink-config.txt but block their ssid and psk?

**Comment by DasKatzchen** [comment]
Is Network Not Found the actual name of your network? Because in my experience, spaces cause all kinds of problems.

**Comment by ConnorRigby** [comment]
After a quick look, it looks like there is a bug in the hastily put together config file parser do-dad. If the the config line starts with a space, it will just hang forever. Just made a fix for this, and will probably put a release together later.

**Comment by ConnorRigby** [comment]
After working with @NutymcNuty for a while this afternoon, i seem to have fixed the issue with WiFi.
https://github.com/ConnorRigby/xlink-kai/releases/download/v0.1.4/xlink-rpi0-v0.1.4.img

Feel free to reopen if something is still broken.
