### ISSUE TITLE
Pi Zero won't boot properly

### ISSUE THREAD

**Issue by DasKatzchen** [ConnorRigby/xlink-kai#2]
using the 1.2 pi zero image on a zero W. Plugged in an hdmi cable and watched the bootup. Seems to mess up about here:
```
mmc1: new high speed SDIO card at address 0001
erlinit:error setting controlling terminal: /dev/ttyS0
EXT4-fs (mmcblk0p3): VFS: Can't find ext4 filesystem
erlinit: Cannot mount /dev/mmcblk0p3 at /root: Invalid argument
erlinit: Specified boot file 'bootloader' not found. Auto-detecting.
Found more than one boot file. Using shoehorn.boot.
```

Something seems to be wrong with mounting partition 3. nothing after that works. Tried the 1.2 pi 3 image (on a pi 3, obviously) and got a similar error, ending with the behavior described in #1 . The 1.1 release works fine on the pi 3.

**Comment by ConnorRigby** [comment]
Interesting. I never tried this out on zero w. Do you run OSX or Linux?

**Comment by DasKatzchen** [comment]
I run whatever I need to run. Spun up an Ubuntu VM and it refuses to mount partition 3. I think something is wrong with your build environment.

**Comment by ConnorRigby** [comment]
Partition 3 won't mount since its not really a real partition. That error message you are getting isn't really _the_ issue. That partition can't mount because it isn't formatted as ext4. Shortly after that message, it should format that partition, then re mount it again. I'm going to dig up an rpi0w and see what is going on. FWIW if you pass thru the usb gadget to your VM you should see a serial port available. if you open that using `screen` or similar you can see the full log.

**Comment by DasKatzchen** [comment]
Huh.that explains a lot. I'll have to check that out when I get home. It should be noted that the 1.2 release doesn't work on pi3 either, so it's not just the pi0w. If I can find my pi2 I could test that as well.

**Comment by ConnorRigby** [comment]
How did you confirm not working on rpi3? i've been using it for about a month

**Comment by DasKatzchen** [comment]
Oh, and you might have problems actually connecting with the wifi. I don't know what build of arm linux you're using, but at least on dreampi which is raspbian based, you have to run tcpdump as a daemon, dumping to /dev/null, in order to convince the wifi driver to connect correctly. this may only be a problem on dreampi, though.

**Comment by ConnorRigby** [comment]
That has never been a problem for me. This "build" is based on "buildroot". i use it for more than one production system, and have never had an issue with wifi connecting. Could you open another issue with any problems you had with connection?

**Comment by DasKatzchen** [comment]
I mean, I haven't even gotten it to boot on the pi0w. I was just throwing that out in case you got it booting and then couldn't get it to hold a connection. It has no problems on the pi3.

**Comment by ConnorRigby** [comment]
I only have a rpi0 (not the w) handy. I can test it out and see if anything terrible happens, but being that it has no network interface i can't test extensively. I will give it another look when i get home tonight with a real rpi0w

**Comment by DasKatzchen** [comment]
I confirmed not working on the pi3 by installing 1.1 and booting and it worked fine, showed up on the network and everything. When I install 1.2 on the same card, same pi3 it never connects to the network, and if I have HDMI plugged in, the last message is "random: nonblocking pool is initialized" as in #1. will comment more in that specific issue.

**Comment by DasKatzchen** [comment]
On the pi0w I can see the serial port, but when I try to connect, screen terminates immediately

**Comment by ConnorRigby** [comment]
You need permissions to it. Try adding yourself to `dialout` or just using
`sudo`

**Comment by ConnorRigby** [comment]
I just tested out the latest release on rpi0, and it seemed to work. 
`https://github.com/ConnorRigby/xlink-kai/releases/download/v0.1.4/xlink-rpi0-v0.1.4.img`

Feel free to re open if you still have issues.
