### ISSUE TITLE
No "src/libkaiui/" Directory

### ISSUE THREAD

**Issue by elmorejd** [ConnorRigby/xlink-kai#3]
Trying to build this from source and it looks like I am missing something important...

`cd src/libkaiui/; make`
 `/bin/sh: line 0: cd: src/libkaiui/: No such file or directory`

**Comment by elmorejd** [comment]
LibKaiUI can be found at http://libkaiui.sourceforge.net/ for those interested.
The next issue is libkai_port. I haven't figured out what/where that is located.

**Comment by ConnorRigby** [comment]
Hello sorry but the `Makefile` in this repo isn't actually used for anything. I started building out a feature but never got around to finishing it. I'll remove the Makefile and c source to prevent this from happening.

**Comment by ConnorRigby** [comment]
I released V0.2.0 which removes this stuff to avoid confusion. Thanks for the issue!
